# Generated by Django 4.1.7 on 2023-03-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_answer_type_question_type_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
