# Generated by Django 4.1.7 on 2023-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
