# Generated by Django 4.1.7 on 2023-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
