# Generated by Django 4.1.7 on 2023-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
