# Generated by Django 4.1.7 on 2023-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(max_length=510),
        ),
    ]
