# Generated by Django 4.1.7 on 2023-03-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_passedanswers_passed_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassedAnswers',
            new_name='PassedAnswer',
        ),
    ]
