# Generated by Django 4.1.7 on 2023-03-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_question_name_alter_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passedanswer',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
