# Generated by Django 4.1.7 on 2023-03-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_test_deadline_alter_answer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passedtest',
            old_name='date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='deadline',
            new_name='date',
        ),
        migrations.AddField(
            model_name='passedtest',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
