# Generated by Django 4.1.7 on 2023-03-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_rename_date_passedtest_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='time',
        ),
    ]
