# Generated by Django 4.1.7 on 2023-05-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_testsettings_alter_passedtest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
