# Generated by Django 4.1.7 on 2023-05-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.answer'),
        ),
    ]
