# Generated by Django 4.1.7 on 2023-09-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_passedtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_questions', to='tests.question'),
        ),
        migrations.AlterField(
            model_name='passedquestion',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
