export default [
    {
        rules: {
            'react/checked-requires-onchange-or-readonly': 'warn',
            'react/default-props-match-prop-types': 'warn',
            'react/destructuring-assignment': ['warn', 'always'],
            'react/display-name': 'warn',
            // 'react/forbid-component-props': ['warn', { forbid: { disallowedFor: ['Form', 'Icon'] } }],
            'react/forbid-foreign-prop-types': 'warn',
            'react/function-component-definition': ['warn', { namedComponents: 'arrow-function', unnamedComponents: 'arrow-function' }],
            'react/hook-use-state': 'warn',
            'react/iframe-missing-sandbox': 'warn',
            'react/jsx-boolean-value': ['warn', 'always'],
            'react/jsx-child-element-spacing': 'warn',
            'react/jsx-closing-bracket-location': 'warn',
            'react/jsx-closing-tag-location': 'warn',
            'react/jsx-curly-newline': 'warn',
            'react/jsx-curly-spacing': 'warn',
            'react/jsx-equals-spacing': 'warn',
            'react/jsx-filename-extension': ['warn', { extensions: ['.jsx', '.tsx'] }],
            'react/jsx-first-prop-new-line': 'warn',
            'react/jsx-fragments': 'warn',
            'react/jsx-indent': ['warn', 4],
            'react/jsx-indent-props': ['warn', 4],
            'react/jsx-key': ['error', { checkFragmentShorthand: true, checkKeyMustBeforeSpread: true, warnOnDuplicates: true }],
            'react/jsx-max-depth': ['warn', { max: 6 }],
            'react/jsx-max-props-per-line': ['warn', { maximum: { single: 4, multi: 1 } }],
            'react/jsx-newline': ['warn', { prevent: true, allowMultilines: true }],
            'react/jsx-no-comment-textnodes': 'error',
            'react/jsx-no-constructed-context-values': 'warn',
            'react/jsx-no-duplicate-props': 'warn',
            'react/jsx-no-leaked-render': ['warn', { validStrategies: ['coerce'] }],
            'react/jsx-no-undef': ['error', { allowGlobals: false }],
            'react/jsx-no-useless-fragment': 'warn',
            'react/jsx-one-expression-per-line': 'warn',
            'react/jsx-pascal-case': 'warn',
            'react/jsx-props-no-multi-spaces': 'warn',
            'react/jsx-tag-spacing': 'warn',
            'react/jsx-uses-react': 'warn',
            'react/jsx-uses-vars': 'warn',
            'react/jsx-wrap-multilines': ['warn', {
                declaration: 'parens-new-line',
                return: 'parens-new-line',
                arrow: 'parens-new-line',
                condition: 'parens-new-line',
                logical: 'parens-new-line',
                assignment: 'parens-new-line',
            }],
            'react/no-access-state-in-setstate': 'error',
            'react/no-children-prop': 'error',
            'react/no-danger': 'error',
            'react/no-danger-with-children': 'error',
            'react/no-deprecated': 'error',
            'react/no-did-mount-set-state': 'error',
            'react/no-did-update-set-state': 'error',
            'react/no-direct-mutation-state': 'error',
            'react/no-find-dom-node': 'error',
            'react/no-direct-mutation-state': 'error',
            'react/no-invalid-html-attribute': 'warn',
            'react/no-is-mounted': 'error',
            'react/no-multi-comp': 'warn',
            'react/no-namespace': 'error',
            'react/no-redundant-should-component-update': 'warn',
            'react/no-render-return-value': 'warn',
            'react/no-string-refs': 'warn',
            'react/no-this-in-sfc': 'warn',
            'react/no-typos': 'warn',
            'react/no-unescaped-entities': 'error',
            'react/no-unknown-property': 'warn',
            'react/no-unsafe': 'error',
            'react/no-unstable-nested-components': 'warn',
            'react/no-unused-class-component-methods': 'warn',
            'react/no-unused-prop-types': 'warn',
            'react/no-unused-state': 'warn',
            'react/no-will-update-set-state': 'error',
            'react/prefer-es6-class': 'error',
            'react/prop-types': 'warn',
            'react/require-render-return': 'warn',
            'react/self-closing-comp': 'error',
        },
    },
];
// 'react/jsx-props-no-spreading':
