# Generated by Django 4.1.7 on 2023-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='color',
        ),
    ]
