# Generated by Django 4.1.7 on 2023-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
