# Generated by Django 4.1.7 on 2023-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
