# Generated by Django 4.1.7 on 2023-03-14 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_class_description_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
