# Generated by Django 4.1.7 on 2023-03-14 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
