# Generated by Django 4.1.7 on 2023-03-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classes.class'),
        ),
    ]
