# Generated by Django 4.1.7 on 2023-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_member__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
