# Generated by Django 4.1.7 on 2023-05-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_classtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='classes.class')),
                ('allow_view_members_list', models.BooleanField(default=True)),
            ],
        ),
    ]
