# Generated by Django 4.1.7 on 2023-05-01 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_classsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingmember',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='classes.class'),
        ),
    ]
